### ISSUE TITLE
5.0.0 has a regression with savon versions that depend on httpi

### ISSUE THREAD

**Issue by pcai** [savonrb/wasabi#117]
regression is probably from: https://github.com/savonrb/wasabi/pull/116

repro:
- check out savon main at a recent version, e.g., [13c4d7d41944d295f4706b813b3aaaabeb11cd39](https://github.com/savonrb/savon/commit/13c4d7d41944d295f4706b813b3aaaabeb11cd39)
- bundle, make sure wasabi 5.0 is installed
- run tests

expected:
- tests pass

actual:

(truncated, but this is a representative example):
 
```
5) Savon::Client#build_request returns the request without making an actual call
     Failure/Error: unless wsdl.soap_actions.include? operation_name
     
     NoMethodError:
       undefined method `get' for #<HTTPI::Request:0x00007f1871997d58 @read_timeout=10, @follow_redirect=false, @open_timeout=10>
     # /usr/local/rvm/gems/default/gems/wasabi-5.0.0/lib/wasabi/resolver.rb:45:in `load_from_remote'
     # /usr/local/rvm/gems/default/gems/wasabi-5.0.0/lib/wasabi/resolver.rb:35:in `resolve'
     # /usr/local/rvm/gems/default/gems/wasabi-5.0.0/lib/wasabi/document.rb:144:in `xml'
     # /usr/local/rvm/gems/default/gems/wasabi-5.0.0/lib/wasabi/document.rb:162:in `parse'
     # /usr/local/rvm/gems/default/gems/wasabi-5.0.0/lib/wasabi/document.rb:149:in `parser'
     # /usr/local/rvm/gems/default/gems/wasabi-5.0.0/lib/wasabi/document.rb:66:in `soap_actions'
     # ./lib/savon/operation.rb:29:in `ensure_exists!'
     # ./lib/savon/operation.rb:22:in `create'
     # ./lib/savon/client.rb:33:in `operation'
     # ./lib/savon/client.rb:37:in `call'
     # ./spec/support/integration.rb:5:in `call_and_fail_gracefully'
     # ./spec/integration/zipcode_example_spec.rb:23:in `block (4 levels) in <top (required)>'
```

**Comment by pcai** [comment]
resolved in https://github.com/savonrb/wasabi/commit/240e10f5f8a7639d2650476df440467388177939
