### ISSUE TITLE
undefined method `element_children' for nil:NilClass parser.rb:318

### ISSUE THREAD

**Issue by janhh** [savonrb/wasabi#49]
Hi, I receive a "undefined method" message at parser.rb:318. See attached screenshot, and the code in link.
https://github.com/savonrb/wasabi/blob/v3.3.1/lib/wasabi/parser.rb#L318

The \@messages object is an empty hash and the port_message_type variable has a variable. Savon mocks the service I am testing against.

If I add a "if message" at the end of line 320, my rspec fails at parser.rb:260 with same error message. Interestingly, adding if check made test pass when I used wasabi 3.3.0 IIRC.

![screenshot from 2014-10-02 16 29 43](https://cloud.githubusercontent.com/assets/706499/4492463/593b32ae-4a41-11e4-83e9-0e3a8df60ea8.png)

**Comment by sshaw** [comment]
The problem occurs when [an HTML doc is returned by a server](https://github.com/savonrb/wasabi/tree/v3.3.1/lib/wasabi/document.rb#L142) and passed [to `Nokogiri.XML`](https://github.com/savonrb/wasabi/tree/v3.3.1/lib/wasabi/document.rb#L160). In this case the document's root in `nil`:

```
irb [2.1.3] (sshaw-savon)$ Nokogiri::XML("<!doctype html><head></head><body></body>").root
=> nil
```

You can reproduce this using Savon with:
```ruby
client = Savon.client(wsdl: "http://example.com")               
client.call(:xxxx, message: "Death to Saxon!")
```

The result:
```
/Users/sshaw/.rvm/gems/ruby-2.1.3/gems/wasabi-3.3.0/lib/wasabi/parser.rb:311:in `sections': undefined method `element_children' for nil:NilClass (NoMethodError)
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/wasabi-3.3.0/lib/wasabi/parser.rb:304:in `section'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/wasabi-3.3.0/lib/wasabi/parser.rb:294:in `schemas'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/wasabi-3.3.0/lib/wasabi/parser.rb:67:in `parse_namespaces'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/wasabi-3.3.0/lib/wasabi/parser.rb:54:in `parse'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/wasabi-3.3.0/lib/wasabi/document.rb:161:in `parse'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/wasabi-3.3.0/lib/wasabi/document.rb:147:in `parser'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/wasabi-3.3.0/lib/wasabi/document.rb:64:in `soap_actions'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/savon-2.8.1/lib/savon/operation.rb:21:in `ensure_exists!'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/savon-2.8.1/lib/savon/operation.rb:14:in `create'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/savon-2.8.1/lib/savon/client.rb:32:in `operation'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/savon-2.8.1/lib/savon/client.rb:36:in `call'
```

**Comment by tjarratt** [comment]
Hah, great catch @sshaw! I think the fix for this would be to catch this and return an error in this case, rather than trying to parse an HTML body. Will see if I can find time to fix this sometime next week, but if someone wants to issue a PR for this I'd be more than happy to help out.
